spring:
  application:
    name: fashionshop

  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=FashionDB;encrypt=true;trustServerCertificate=true
    username: sa
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update   # Hoặc validate nếu DB đã có sẵn
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
